### ISSUE TITLE
Github vs Pypi, xesmf vs pangeo-xesmf

### ISSUE THREAD

**Issue by zklaus** [conda-forge/xesmf-feedstock#27]
### Comment:

We are having some trouble figuring out how best approach depending on xesmf.

Generally speaking, we declare all our dependencies in setup.py, but usually install everything from conda-forge. I consider this best practice because it leaves the user options on how to install dependencies, be that via their distributions package manager, from source, or whatever.

In the case of xesmf, this presents a conundrum because what will invariably be perceived as the official releases on Pypi use the name `pangeo-xesmf`, whereas in parallel releases on the github page and on conda-forge use the name `xesmf`. Note that this is not about the name of the conda-forge package, which is quite frequently different from the Pypi name, but about the dist-info inside of it.

How should this be addressed? Why are we using the Github releases instead of the Pypi ones and why are those built in different ways anyway?

**Comment by ocefpaf** [comment]
It would be nice to raise those issues upstream in the pangeo-xesmf fork. The fork, and the PyPI rename, exists b/c the creator of the library went MIA and was the sole owner of the repo and PyPI namespace. So, to be able to continue with the project, the maintainers had to fork and rename it on PyPI. However, it is essentially the same software.

**Comment by zklaus** [comment]
I opened pangeo-data/xESMF#183 to discuss this. Regardless, I think building from the PyPI release could be an option for conda-forge.

**Comment by zklaus** [comment]
The upstream issue was resolved by recovering access to the PyPI project `xesmf`, see pangeo-data/xESMF#183 :tada:. Starting with version 0.7.1 we can now build consistently from the PyPI releases again.
