### ISSUE TITLE
Pin shapely too.

### ISSUE THREAD

**Issue by aulemahal** [conda-forge/xesmf-feedstock#28]
I'm not sure how "feedstocks" work, but the last update didn't add the pin to `shapely`, which makes the build fail and prevents from uploading version 0.7 to conda-forge.

I do not have write access to this repo, but it looks like only this line needs to be changed:

https://github.com/conda-forge/xesmf-feedstock/blob/322d1b7bd544a22140b956202d7451973075660a/recipe/meta.yaml#L26

@huard ?

**Comment by ocefpaf** [comment]
See https://github.com/conda-forge/xesmf-feedstock/commit/322d1b7bd544a22140b956202d7451973075660a
