### ISSUE TITLE
xESMF can pull in unimportable ESMPy 8.4.* as dependency

### ISSUE THREAD

**Issue by DWesl** [conda-forge/xesmf-feedstock#43]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

ESMPy 8.4 changed from specifying authors in both `setup.py` and the package `__init__.py` to only in `setup.py`, using `importlib_metadata` to grab the metadata from the package `dist-info`, then moved the whole system to `pyproject.toml` with no `setup.py`, during which the list of authors got dropped but the code to get them from `dist-info` did not.  (esmf-org/esmf#58)

At the time, this was not an issue, as `importlib_metadata` produced a result of `None` when asked for metadata not provided by the package.  This changed to `DeprecationWarning`s, which prompted a fix before ESMPy 8.5 (esmf-org/esmf#140), and eventually to `KeyError`, which caused an `ImportError`.

This is already on the xESMF repo as pangeo-data/xESMF#374

Would it be possible to change the requirements from `ESMPy>=8.0` to `ESMPy>=8.0, !=8.4.0, !=8.4.1, !=8.4.2`?  I'm not sure where that gets set, or I'd make the PR myself.

### Installed packages
```
ESMPy==8.4.1
python==3.11
xesmf
pynio
```
### Environment info
```
Linux server
```

**Comment by ocefpaf** [comment]
> Would it be possible to change the requirements from ESMPy>=8.0 to ESMPy>=8.0, !=8.4.0, !=8.4.1, !=8.4.2? I'm not sure where that gets set, or I'd make the PR myself.

It would exactly what you posted there ,without the spaces after the commas:

```
ESMPy >=8.0,!=8.4.0,!=8.4.1,!=8.4.2
```
